# Generated by Django 6.0.5 on 2026-05-24 21:29

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=20, unique=True)),
                ('face_encoding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=students.models.renomear_foto_perfil)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('active_now', models.BooleanField(default=False)),
                ('total_hours', models.IntegerField(default=60, help_text='Carga horária total da disciplina')),
                ('hours_taught', models.IntegerField(default=0, help_text='Total de horas já ministradas')),
                ('start_time', models.TimeField(blank=True, help_text='Ex: 14:00', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Ex: 16:00', null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_taught', to=settings.AUTH_USER_MODEL)),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='my_classes', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('liveness_score', models.FloatField()),
                ('is_valid', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('ENTRADA', 'Entrada (Esquerda para Direita)'), ('SAÍDA', 'Saída (Direita para Esquerda)')], default='ENTRADA', max_length=10)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
