# Generated by Django 6.0.4 on 2026-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='my_classes', to='students.student'),
        ),
    ]
