# Generated by Django 6.0.5 on 2026-05-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_attendance_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp']},
        ),
    ]
