# Generated by Django 6.0.5 on 2026-05-22 17:40

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.renomear_foto_perfil),
        ),
    ]
