# Generated by Django 6.0.5 on 2026-05-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Ex: 16:00', null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Ex: 14:00', null=True),
        ),
    ]
