# Generated by Django 6.0.5 on 2026-05-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_classroom_end_time_classroom_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='hours_taught',
            field=models.IntegerField(default=0, help_text='Total de horas já ministradas'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='total_hours',
            field=models.IntegerField(default=60, help_text='Carga horária total da disciplina'),
        ),
    ]
